apiVersion: v1
kind: Pod
metadata:
  name: test-pod
  namespace: default
  labels:          # Service와 연결을 위한 labels 추가
    app: nginx
spec:
  containers:
  - name: nginx
    image: nginx:latest
    ports:
    - containerPort: 80

